"""estrutura com unidades de
  equipamento

Revision ID: d3633e99f311
Revises: 
Create Date: 2026-08-08 23:14:09.981905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3633e99f311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('equipamento',
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_equipamento')
    )
    op.create_table('tecnico',
    sa.Column('id_tecnico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_tecnico'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('unidade_equipamento',
    sa.Column('id_unidade_equipamento', sa.Integer(), nullable=False),
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('numero_patrimonio', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_equipamento'], ['equipamento.id_equipamento'], ),
    sa.PrimaryKeyConstraint('id_unidade_equipamento'),
    sa.UniqueConstraint('numero_patrimonio')
    )
    op.create_table('emprestimo',
    sa.Column('id_emprestimo', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_unidade_equipamento', sa.Integer(), nullable=False),
    sa.Column('id_tecnico_retirada', sa.Integer(), nullable=False),
    sa.Column('id_tecnico_devolucao', sa.Integer(), nullable=True),
    sa.Column('data_hora_emprestimo', sa.DateTime(), nullable=False),
    sa.Column('data_hora_prevista_devolucao', sa.DateTime(), nullable=False),
    sa.Column('data_hora_devolucao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_tecnico_devolucao'], ['tecnico.id_tecnico'], ),
    sa.ForeignKeyConstraint(['id_tecnico_retirada'], ['tecnico.id_tecnico'], ),
    sa.ForeignKeyConstraint(['id_unidade_equipamento'], ['unidade_equipamento.id_unidade_equipamento'], ),
    sa.PrimaryKeyConstraint('id_emprestimo')
    )
    op.create_table('pendencia',
    sa.Column('id_pendencia', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_emprestimo', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_emprestimo'], ['emprestimo.id_emprestimo'], ),
    sa.PrimaryKeyConstraint('id_pendencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendencia')
    op.drop_table('emprestimo')
    op.drop_table('unidade_equipamento')
    op.drop_table('tecnico')
    op.drop_table('equipamento')
    op.drop_table('aluno')
    # ### end Alembic commands ###
